version: 1.0.{build}

build_cloud: GCE

init:
- appveyor version
- ps: |
    Update-AppveyorBuild -Message "Google storage and cache (with nuget 6.0.3)"
    Start-sleep -s 1
    Write-Host "appveyor_build_folder: $env:appveyor_build_folder"
    Write-Host "MY_BUILD_DIR: $env:MY_BUILD_DIR"
    Write-Host "MY_DIST_DIR: $env:MY_DIST_DIR"

cache:
- wxWidgets.7z
- Appveyor.NUnitLogger.zip
- node.zip
- packages

install:
- nuget restore packages.config -PackagesDirectory packages

build_script:
- ps: Start-FileDownload https://www.appveyor.com/downloads/Appveyor.NUnitLogger.zip
- ps: Start-FileDownload 'https://nodejs.org/dist/v6.5.0/node-v6.5.0-darwin-x64.tar.gz' -FileName wxWidgets.7z
- ps: Push-AppveyorArtifact wxWidgets.7z
- fsutil file createnew bigfile 2300000000

test_script:
- appveyor PushArtifact products.zip
- appveyor PushArtifact newtonsoft.json.6.0.3.nupkg
- ps: Set-Content -Path "$env:appveyor_build_folder\packages\ts.txt" -Value "$(get-date)"

artifacts:
- path: 7zip
- path: node.zip
- path: README.md
- path: bigfile
