version: 1.0.{build}

build_cloud: GCE

init:
- appveyor version
- ps: |
    Update-AppveyorBuild -Message "Google storage and cache (with nuget 6.0.3)"
    Start-sleep -s 1
    Write-Host "appveyor_build_folder: $env:appveyor_build_folder"
    Write-Host "MY_BUILD_DIR: $env:MY_BUILD_DIR"
    Write-Host "MY_DIST_DIR: $env:MY_DIST_DIR"

cache:
- wxWidgets.7z
- Appveyor.NUnitLogger.zip
- node.zip
- packages

install:
- nuget restore packages.config -PackagesDirectory packages

test_script:
- appveyor PushArtifact products.zip
- appveyor PushArtifact newtonsoft.json.6.0.3.nupkg
- ps: Set-Content -Path "$env:appveyor_build_folder\packages\ts.txt" -Value "$(get-date)"

artifacts:
- path: README.md
